name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Permission check
        run: git config --global --add safe.directory /github/workspace
      - name: Permission check #2
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Permission check #3
        run: export GIT_CEILING_DIRECTORIES=/github/workspace
      - name: Checkout
        uses: actions/checkout@main
      - name: Firebase App Distribution Action
        uses: ./
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_TOKEN}}
          app_file: app-release-ac-signed.apk
          tester_groups: maintainers

